f = open("file.txt", "rt")
print(f.read())
f.close()
#f = open("file.txt", "x")
#f.write("None")
#f.close()
f = open("file.txt", "w")
f.write("None")
f.close()
f = open("file.txt", "a")
f.write("None")
f.close()